header_include_path: teraranger/teraranger.hpp
namespace: Teraranger
node_class_name: TerarangerNode

params:
  cov_good:
    type: double
    default_value: 0.01
    min_value: 0.0
    max_value: 1000.0
    step: 0.0
    description: "Covariance value when laser is measuring."
    constraints: "Cannot be changed."
    read_only: true
    var_name: cov_good

  cov_bad:
    type: double
    default_value: 0.01
    min_value: 0.0
    max_value: 1000.0
    step: 0.0
    description: "Covariance value when laser is not measuring."
    constraints: "Cannot be changed."
    read_only: true
    var_name: cov_bad

  delta_max:
    type: double
    default_value: 0.01
    min_value: 0.0
    max_value: 1.0
    step: 0.0
    description: "Maximum difference between reference and current height."
    constraints: "Can be changed."
    read_only: false
    var_name: delta_max

  field_of_view:
    type: double
    default_value: 0.01
    min_value: 0.0
    max_value: 1.0
    step: 0.0
    description: "Laser field of view."
    constraints: "Can be changed."
    read_only: false
    var_name: field_of_view

  frame_base:
    type: string
    default_value: base_link
    description: "Fmu frame name"
    constraints: "Cannot be changed"
    read_only: true
    var_name: frame_base

  frame_fmu:
    type: string
    default_value: fmu_link
    description: "Fmu frame name"
    constraints: "Cannot be changed"
    read_only: true
    var_name: frame_fmu

  frame_laser:
    type: string
    default_value: laser_link
    description: "Laser frame name"
    constraints: "Cannot be changed"
    read_only: true
    var_name: frame_laser

  frame_map:
    type: string
    default_value: map
    description: "Map frame name"
    constraints: "Cannot be changed"
    read_only: true
    var_name: frame_map

  frame_odom:
    type: string
    default_value: odom
    description: "Odom frame name"
    constraints: "Cannot be changed"
    read_only: true
    var_name: frame_odom

  laser_bias:
    type: double
    default_value: 0.0
    min_value: -1.0
    max_value: 1.0
    step: 0.0
    description: "Laser bias in meters."
    constraints: "Can be changed."
    read_only: false
    var_name: laser_bias

  port:
    type: string
    default_value: /dev/12c
    description: "I²C port."
    constraints: "Cannot be changed."
    read_only: true
    var_name: port

  publish_range:
    type: bool
    default_value: true
    description: "Flag to publish range data."
    constraints: "Cannot be changed."
    read_only: true
    var_name: publish_range

  publish_altitude:
    type: bool
    default_value: true
    description: "Flag to publish altitude data."
    constraints: "Cannot be changed."
    read_only: true
    var_name: publish_altitude

  range_max:
    type: double
    default_value: 0.01
    min_value: 0.0
    max_value: 10.0
    step: 0.0
    description: "Maximum laser range."
    constraints: "Cannot be changed."
    read_only: true
    var_name: range_max

  range_min:
    type: double
    default_value: 0.01
    min_value: 0.0
    max_value: 10.0
    step: 0.0
    description: "Minimum laser range."
    constraints: "Cannot be changed."
    read_only: true
    var_name: range_min

  timer_frequency:
    type: integer
    default_value: 10
    min_value: 1
    max_value: 1000
    step: 1
    description: "Timer frequency."
    constraints: "Cannot be changed."
    read_only: true
    var_name: timer_frequency

  topic_altitude:
    type: string
    default_value: /ref
    description: "Topic name for the altitude message."
    constraints: "Cannot be changed."
    read_only: true
    var_name: topic_altitude

  topic_range:
    type: string
    default_value: /range_topic
    description: "Topic name for Range msg publication."
    constraints: "Cannot be changed."
    read_only: true
    var_name: topic_range