header_include_path: teraranger/teraranger.hpp
namespace: Teraranger
node_class_name: TerarangerNode

params:
  altitude_topic:
    type: string
    default_value: /ref
    description: "Topic name for the altitude message."
    constraints: "Cannot be changed."
    read_only: true
    var_name: altitude_topic

  cov_good:
    type: double
    default_value: 0.01
    min_value: 0.0
    max_value: 1000.0
    step: 0.0
    description: "Covariance value when laser is measuring."
    constraints: "Cannot be changed."
    read_only: true
    var_name: cov_good

  cov_bad:
    type: double
    default_value: 0.01
    min_value: 0.0
    max_value: 1000.0
    step: 0.0
    description: "Covariance value when laser is not measuring."
    constraints: "Cannot be changed."
    read_only: true
    var_name: cov_bad

  delta_max:
    type: double
    default_value: 0.01
    min_value: 0.0
    max_value: 1.0
    step: 0.0
    description: "Maximum difference between reference and current height."
    constraints: "Can be changed."
    read_only: false
    var_name: delta_max

  link_namespace:
    type: string
    default_value: drone/
    description: "Drone link namespace, including the trailing slash"
    constraints: "Cannot be changed"
    read_only: true
    var_name: link_namespace

  port:
    type: string
    default_value: /dev/12c
    description: "I²C port."
    constraints: "Cannot be changed."
    read_only: true
    var_name: port

  pose_topic:
    type: string
    default_value: /drone_pose
    description: "Topic name for drone pose."
    constraints: "Cannot be changed."
    read_only: true
    var_name: pose_topic

  publish_range:
    type: bool
    default_value: true
    description: "Flag to publish Range or PoseWithCovarianceStamped msg."
    constraints: "Cannot be changed."
    read_only: true
    var_name: publish_range

  range_topic:
    type: string
    default_value: /range_topic
    description: "Topic name for Range msg publication."
    constraints: "Cannot be changed."
    read_only: true
    var_name: range_topic

  timer_frequency:
    type: integer
    default_value: 10
    min_value: 1
    max_value: 1000
    step: 1
    description: "Timer frequency."
    constraints: "Cannot be changed."
    read_only: true
    var_name: timer_frequency