/teraranger:
  ros__parameters:
    cov_bad: 10.0
    cov_good: 0.001
    delta_max: 0.3
    field_of_view: 0.0349066
    frame_base: stanis/base_link
    frame_fmu: stanis/fmu_link
    frame_laser: stanis/laser_link
    frame_map: map
    frame_odom: stanis/odom
    laser_bias: 0.07
    port: /dev/i2c-8
    publish_altitude: false
    publish_range: true
    range_max: 3.0
    range_min: 0.1
    timer_frequency: 10
    topic_altitude: /altitude
    topic_range: /range
